//! Numeric parity of the candle forward pass against a float32 torch reference
//! (fixture generated by `src_python/tools/dump_parity.py`).

use candle_core::{Device, Tensor};
use serde::Deserialize;

use gen_music_ai::assets;
use gen_music_ai::core::model::config::ModelConfig;
use gen_music_ai::core::model::midi_model::MidiModel;

#[derive(Deserialize)]
struct Fixture {
    prompt: Vec<Vec<u32>>,
    hidden: Vec<f32>,
    logits0: Vec<f32>,
    greedy0: u32,
    logits1: Vec<f32>,
    greedy1: u32,
}

fn max_abs_diff(a: &[f32], b: &[f32]) -> f32 {
    a.iter()
        .zip(b)
        .map(|(x, y)| (x - y).abs())
        .fold(0.0, f32::max)
}

fn cosine(a: &[f32], b: &[f32]) -> f32 {
    let dot: f32 = a.iter().zip(b).map(|(x, y)| x * y).sum();
    let na: f32 = a.iter().map(|x| x * x).sum::<f32>().sqrt();
    let nb: f32 = b.iter().map(|x| x * x).sum::<f32>().sqrt();
    dot / (na * nb)
}

fn argmax(values: &[f32]) -> u32 {
    let mut best = 0u32;
    let mut best_v = f32::NEG_INFINITY;
    for (i, &v) in values.iter().enumerate() {
        if v > best_v {
            best_v = v;
            best = i as u32;
        }
    }
    best
}

fn to_vec(tensor: &Tensor) -> Vec<f32> {
    tensor.flatten_all().unwrap().to_vec1::<f32>().unwrap()
}

#[test]
fn candle_forward_matches_torch_f32() {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/parity.json");
    let fixture: Fixture = serde_json::from_str(&std::fs::read_to_string(path).unwrap()).unwrap();

    let device = Device::Cpu;
    let config = ModelConfig::from_json(assets::CONFIG_JSON).unwrap();
    let model = MidiModel::load(config, device.clone()).unwrap();

    let events = fixture.prompt.len();
    let flat: Vec<u32> = fixture.prompt.iter().flatten().copied().collect();
    let ids = Tensor::from_vec(flat, (1, events, 8), &device).unwrap();

    let mut base_cache = model.base_cache();
    let hidden = model.base_forward(&ids, &mut base_cache).unwrap();
    let hidden_rs = to_vec(&hidden);

    let mut token_cache = model.token_cache();
    let logits0 = to_vec(&model.token_logits_from_hidden(&hidden, &mut token_cache).unwrap());

    // Feed the reference greedy id so step 1 stays aligned regardless of ties.
    let prev = Tensor::from_vec(vec![fixture.greedy0], (1, 1), &device).unwrap();
    let logits1 = to_vec(&model.token_logits_from_id(&prev, &mut token_cache).unwrap());

    eprintln!(
        "hidden: max_abs_diff={:.4} cosine={:.6}",
        max_abs_diff(&hidden_rs, &fixture.hidden),
        cosine(&hidden_rs, &fixture.hidden),
    );
    eprintln!(
        "logits0: max_abs_diff={:.4} cosine={:.6} argmax_rs={} ref={}",
        max_abs_diff(&logits0, &fixture.logits0),
        cosine(&logits0, &fixture.logits0),
        argmax(&logits0),
        fixture.greedy0,
    );
    eprintln!(
        "logits1: max_abs_diff={:.4} cosine={:.6} argmax_rs={} ref={}",
        max_abs_diff(&logits1, &fixture.logits1),
        cosine(&logits1, &fixture.logits1),
        argmax(&logits1),
        fixture.greedy1,
    );

    assert_eq!(argmax(&logits0), fixture.greedy0, "token step 0 greedy id");
    assert_eq!(argmax(&logits1), fixture.greedy1, "token step 1 greedy id");
    assert!(cosine(&hidden_rs, &fixture.hidden) > 0.9999, "hidden cosine");
    assert!(cosine(&logits0, &fixture.logits0) > 0.9999, "logits0 cosine");
    assert!(cosine(&logits1, &fixture.logits1) > 0.9999, "logits1 cosine");
}
